espaco/urls.py
from django.urls import path

from . import views

app_name = 'espaco'

urlpatterns = [
    path('', views.home),
    path('painel/', views.painel, name='painel'),
    path('clientes/', views.clientes, name='clientes'),
    path('verclientes/<int:pessoa_id>', views.ver_cliente, name='ver_cliente'),
    path('delete/<int:pessoa_id>', views.excluircliente, name='excluircliente'),
    path('editar/<int:pessoa_id>', views.editarcliente, name="editarcliente"),
    path('update/<int:pessoa_id>', views.update, name="update"),
    path('atendimentos/', views.meusatendimentos, name="meusatendimentos"),
    path('busca/', views.busca, name='busca'),
    path('buscaatend/', views.buscaatend, name='buscaatend'),
    path('novoatendimento/', views.novoatend, name='novoatend'),
    path('veratendimento/<atendimento_id>', views.veratendimento, name='veratendimento'),
    path('excluiratendimento/<atendimento_id>', views.excluiratendimento, name='excluiratendimento'),
    path('atendeditar/<int:atendimento_id>', views.editaratendimento, name="editaratendimento"),
    path('atendupdate/<int:atendimento_id>', views.atendupdate, name="atendupdate"),
    


]

pagina/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('espaco.urls')),
    path('usuarios/', include('usuarios.urls'))
]

espaco/models.py
from django.db import models


# Create your models here.
class Pessoa(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    cpf = models.CharField(max_length=20, blank=True, null=True)
    datenasc = models.CharField(max_length=12, blank=True, null=True)
    profissao = models.CharField(max_length=50, blank=True, null=True)
    endereco = models.CharField(max_length=100, blank=True, null=True)
    cidade = models.CharField(max_length=60, blank=True, null=True)
    uf = models.CharField(max_length=40, blank=True, null=True)
    pais = models.CharField(max_length=50, blank=True, null=True)
    email = models.CharField(max_length=100, blank=True, null=True)
    telefone = models.CharField(max_length=20, blank=True, null=True)
    genero = models.CharField(max_length=25, blank=True, null=True)
    obsrecepcao = models.TextField(blank=True, null=True)
    filhos = models.CharField(max_length=25, blank=True, null=True)
    idade = models.CharField(max_length=15, blank=True, null=True)
    opcaosexual = models.CharField(max_length=20, blank=True, null=True)
    doencadiagnosticada = models.CharField(max_length=40, blank=True, null=True)
    fazusodemedicamentos = models.CharField(max_length=40, blank=True, null=True)
    obsterapeuta = models.TextField(blank=True, null=True)
    obscomplementares = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return self.nome



class Atendimentos(models.Model):
    nome = models.CharField(max_length=100, blank=True, null=True)
    cpf = models.CharField(max_length=20)
    tecnicaaplicada = models.CharField(max_length=100, blank=True, null=True)
    queixaprincipal = models.CharField(max_length=100, blank=True, null=True)
    tempoconsulta = models.CharField(max_length=20, blank=True, null=True)
    tempoqueixa = models.CharField(max_length=100, blank=True, null=True)
    tipoconsulta = models.CharField(max_length=20, blank=True, null=True)
    dataatend = models.DateField(auto_now=True)
    medicamentos = models.CharField(max_length=50, blank=True, null=True)
    obsatend = models.TextField(blank=True, null=True)
    
    def __str__(self):
        return str(self.nome)


    

espaco/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import Http404
from django.shortcuts import redirect, render
from django.utils.dateparse import parse_date

from .models import Atendimentos, Pessoa


# Create your views here.
def home(request):
    return render(request, 'espaco/pages/home.html')
@login_required(login_url='/usuarios')
def painel(request):
    if request.method != 'POST':
        return render(request, 'espaco/pages/cadastro.html')
    nome = request.POST.get('name')
    cpf = request.POST.get('cpf')
    datanascimento = request.POST.get('datenasc')
    profissao = request.POST.get('profissao')
    endereco = request.POST.get('endereco')
    cidade = request.POST.get('cidade')
    uf = request.POST.get('uf')
    pais = request.POST.get('pais')
    email = request.POST.get('email')
    telefone = request.POST.get('telefone')
    genero = request.POST.get('gender')
    obsrecepcao = request.POST.get('obsrecepcao')
    idade = request.POST.get('idade')
    filhos = request.POST.get('filhos')
    opcaosexual = request.POST.get('opcaosexual')
    doencadiagnosticadas = request.POST.get('doencadiagnosticadas')
    fazusomedicamentos = request.POST.get('fazusomedicamentos')
    obs_terapeuta = request.POST.get('obs_terapeuta')
    obs_complementar = request.POST.get('obs_complementar')
    Pessoa.objects.create(nome=nome, cpf=cpf, datenasc=datanascimento, profissao=profissao, endereco=endereco, cidade=cidade, uf=uf, pais=pais, email=email, telefone=telefone, genero=genero, obsrecepcao=obsrecepcao, idade=idade, filhos=filhos, opcaosexual=opcaosexual, doencadiagnosticada=doencadiagnosticadas, fazusodemedicamentos=fazusomedicamentos, obsterapeuta=obs_terapeuta, obscomplementares=obs_complementar)
    return render(request, 'espaco/pages/cadastro.html')

@login_required(login_url='/usuarios')
def clientes(request):
    cliente = Pessoa.objects.order_by('-id')
    return render(request, 'espaco/pages/clientes.html', {
        'clientes': cliente
    })
@login_required(login_url='/usuarios')
def ver_cliente(request, pessoa_id):
    cliente = Pessoa.objects.get(id=pessoa_id)
    return render(request, 'espaco/pages/ver_clientes.html', {
        'cliente': cliente
    })
@login_required(login_url='/usuarios')
def excluircliente(request, pessoa_id):
    cliente = Pessoa.objects.get(id=pessoa_id)
    cliente.delete()
    return redirect('espaco:clientes')
@login_required(login_url='/usuarios')
def editarcliente(request, pessoa_id):
    cliente = Pessoa.objects.get(id=pessoa_id)    
    return render(request, 'espaco/pages/update.html', {
        'cliente': cliente
    })
@login_required(login_url='/usuarios')
def update(request, pessoa_id):
    vnome = request.POST.get('name')
    vcpf = request.POST.get('cpf')
    vdatanascimento = parse_date(request.POST.get('datenasc'))
    vprofissao = request.POST.get('profissao')
    vendereco = request.POST.get('endereco')
    vcidade = request.POST.get('cidade')
    vuf = request.POST.get('uf')
    vpais = request.POST.get('pais')
    vemail = request.POST.get('email')
    vtelefone = request.POST.get('telefone')
    vgenero = request.POST.get('gender')
    vobs = request.POST.get('obsrecepcao')
    vidade = request.POST.get('idade')
    vfilhos = request.POST.get('filhos')
    vopcaosexual = request.POST.get('opcaosexual')
    vdoencadiagnosticadas = request.POST.get('doencadiagnosticadas')
    vfazusomedicamentos = request.POST.get('fazusomedicamentos')
    vobs_terapeuta = request.POST.get('obs_terapeuta')
    vobs_complementar = request.POST.get('obs_complementar')
    cliente = Pessoa.objects.get(id=pessoa_id)
    cliente.nome = vnome
    cliente.cpf = vcpf
    cliente.datenasc = vdatanascimento
    cliente.profissao = vprofissao
    cliente.endereco = vendereco
    cliente.cidade = vcidade
    cliente.uf = vuf
    cliente.pais = vpais
    cliente.email = vemail
    cliente.telefone = vtelefone
    cliente.genero = vgenero
    cliente.obsrecepcao = vobs
    cliente.idade = vidade
    cliente.filhos = vfilhos
    cliente.opcaosexual = vopcaosexual
    cliente.doencadiagnosticada = vdoencadiagnosticadas
    cliente.fazusodemedicamentos = vfazusomedicamentos
    cliente.obsterapeuta = vobs_terapeuta
    cliente.obscomplementares = vobs_complementar
    cliente.save()
    return redirect('espaco:clientes')
@login_required(login_url='/usuarios')
def meusatendimentos(request):
    atendimento = Atendimentos.objects.order_by('-id')
    return render(request, 'espaco/pages/meusatendimentos.html', {
        'atendimentos': atendimento
    })

@login_required(login_url='/usuarios')
def busca(request):
    termo = request.GET.get('termo')
    if termo is None or not termo:
        raise Http404()
    cliente = Pessoa.objects.order_by('-id').filter(
        Q(nome__icontains=termo) | Q(cpf=termo) | Q(telefone=termo)
    )
    return render(request, 'espaco/pages/busca.html', {
        'clientes': cliente
    })
@login_required(login_url='/usuarios')
def buscaatend(request):
    busca = request.GET.get('busca')
    if busca is None or not busca:
        raise Http404()
    
    atendimento = Atendimentos.objects.order_by('-id').filter(
        Q(nome__icontains=busca) | Q(tecnicaaplicada__icontains=busca)
    )
    return render(request, 'espaco/pages/buscaatend.html', {
        'atendimentos': atendimento
    })
@login_required(login_url='/usuarios')
def novoatend(request):
    if request.method != ('POST'):
        return render(request, 'espaco/pages/novoatendimento.html')
    nome = request.POST.get('name')
    cpf = request.POST.get('cpf')
    tecnicaaplicada = request.POST.get('tecnicaaplicada')
    tempoconsulta = request.POST.get('tempoconsulta')
    queixaprincipal = request.POST.get('queixaprincipal')
    tipoconsulta = request.POST.get('tipoconsulta')
    tempoqueixa = request.POST.get('tempoqueixa')
    medicamentos = request.POST.get('medicamentos')
    obsatend = request.POST.get('obsatend')
    Atendimentos.objects.create(nome=nome, cpf=cpf, tecnicaaplicada=tecnicaaplicada, queixaprincipal=queixaprincipal, tempoconsulta=tempoconsulta, tipoconsulta=tipoconsulta, medicamentos=medicamentos, tempoqueixa=tempoqueixa, obsatend=obsatend)
    return redirect('espaco:meusatendimentos')
@login_required(login_url='/usuarios')
def veratendimento(request, atendimento_id):
    atendimento = Atendimentos.objects.get(id=atendimento_id)
    return render(request, 'espaco/pages/veratendimento.html', {
        'atendimento': atendimento
    })
@login_required(login_url='/usuarios')
def excluiratendimento(request, atendimento_id):
    atendimento = Atendimentos.objects.get(id=atendimento_id)
    atendimento.delete()
    return redirect('espaco:meusatendimentos')

def editaratendimento(request, atendimento_id):
    atendimento = Atendimentos.objects.get(id=atendimento_id)    
    return render(request, 'espaco/pages/atendupdate.html', {
        'atendimento': atendimento
    })

@login_required(login_url='/usuarios')
def atendupdate(request, atendimento_id):
    vnome = request.POST.get('name')
    vcpf = request.POST.get('cpf')
    vtecnicaaplicada = request.POST.get('tecnicaaplicada')
    vtempoconsulta = request.POST.get('tempoconsulta')
    vqueixaprincipal = request.POST.get('queixaprincipal')
    vtempoqueixa = request.POST.get('tempoqueixa')
    vtipoconsulta = request.POST.get('tipoconsulta')
    vmedicamentos = request.POST.get('medicamentos')
    vobsatend = request.POST.get('obsatend')
    atendimento = Atendimentos.objects.get(id=atendimento_id)
    atendimento.nome = vnome
    atendimento.cpf = vcpf
    atendimento.tecnicaaplicada = vtecnicaaplicada
    atendimento.medicamentos = vmedicamentos
    atendimento.tempoconsulta = vtempoconsulta
    atendimento.queixaprincipal = vqueixaprincipal
    atendimento.tempoqueixa = vtempoqueixa
    atendimento.tipoconsulta = vtipoconsulta
    atendimento.obsatend = vobsatend
    atendimento.save()
    return redirect('espaco:meusatendimentos')

espaco/templates/espaco/pages/atendupdate.html
{% extends 'global/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">
{% block content %}
{% include 'espaco/partials/nav.html' %}

    <main>
        <!--<div tabindex="0" onclick="closeSidebar()" class="content" id="content"></div>-->
        <div tabindex="0" onclick="closeSidebar()" id="content" class="container">
            <!--<div class="form-img">
                <img src="{% static 'img/undraw_medicine_b-1-ol.svg' %}" alt="">
            </div>-->
            <div class="form">
                <form method="POST" action="{% url 'espaco:atendupdate' atendimento.id %}">
                    {% csrf_token %}
                    <div class="form-header">
                        <div class="title">
                            <h1>ADICIONAR ATENDIMENTO</h1>
                        </div>
                    </div>
                    <div class="input-group">
                        <div class="input-box">
                            <label for="name">Nome</label>
                            <input type="text" name="name" id="name" placeholder="NOME" value="{{ atendimento.nome }}">
                        </div>

                        <div class="input-box">
                            <label for="cpf">CPF</label>
                            <input type="text" name="cpf" id="cpf" placeholder="CPF" value="{{ atendimento.cpf }}">
                        </div>

                        

                        <div class="input-box">
                            <label for="tecncaaplicada">Tecnica Aplicada</label>
                            <input type="text" name="tecnicaaplicada" id="tecncaaplicada" value="{{ atendimento.tecnicaaplicada }}">
                        </div>
                        

                        <div class="input-box">
                            <label for="tempoconsulta">Tempo Consulta</label>
                            <input type="text" name="tempoconsulta" id="tempoconsulta" value="{{ atendimento.tempoconsulta }}">
                        </div>

                        <div class="input-box">
                            <label for="queixaprincipal">Queixa Principal</label>
                            <input type="text" name="queixaprincipal" id="queixaprincipal" value="{{ atendimento.queixaprincipal }}">
                        </div>

                        <div class="input-box">
                            <label for="tempoqueixa">Tempo da Queixa</label>
                            <input type="text" name="tempoqueixa" id="tempoqueixa" value="{{ atendimento.tempoqueixa }}">
                        </div>

                        <div class="input-box">
                            <label for="tipoconsulta">Tipo de Consulta</label>
                            <select name="tipoconsulta" id="uf">
                                <option value="{{ atendimento.tipoconsulta }}">{{ atendimento.tipoconsulta }}</option>
                                <option value=""></option>
                                <option value="Online">Online</option>
                                <option value="Presencial">Presencial</option>

                            </select>
                        </div>

                        <div class="input-box">
                            <label for="medicamentos">Medicamentos</label>
                            <input type="text" name="medicamentos" id="medicamentos" value="{{ atendimento.medicamentos }}">
                        </div>

                        <div class="input-box" id="obs">
                            <label for="obsatend">Obs Atendimento:</label>
                            <textarea name="obsatend" id="obs" cols="120" rows="10">{{ atendimento.obsatend }}</textarea>
                        </div>





                    <div class="add-client">
                        <button type="submit"><a href="#"></a>Adicionar Atendimento</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}



</html>

espaco/templates/espaco/pages/busca.html
{% extends 'espaco/pages/clientes.html' %}

espaco/templates/espaco/pages/buscaatend.html
{% extends 'espaco/pages/meusatendimentos.html' %}

espaco/templates/espaco/pages/clientes.html
{% extends 'global/base.html' %}
{% load static %}

{% block content %}
{% include "espaco/partials/nav.html" %}
<main>
    <div class="table-div">
        <table class="table">
            <div class="pesquisa">
                <form method="GET"action="{% url 'espaco:busca' %}">
                    <div class="form-pesquisa">
                        <input type="search" value="{{ request.GET.termo }}" class="form-control" placeholder="Digite sua pesquisa" name="termo">
                    </div>
                </form>
            </div>
            <caption>Meus Clientes</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Cpf</th>
                    <th>Idade</th>
                    <th>Telefone</th>
                </tr>
            </thead>
            <tbody>
                {% for cliente in clientes %}
                <tr>
                    <td>{{ cliente.id }}</td>
                    <td>
                        <a href="{% url 'espaco:ver_cliente'  cliente.id %}">{{ cliente.nome }}</a>
                    </td>
                    <td>{{ cliente.cpf }}</td>
                    <td>{{ cliente.idade }}</td>
                    <td>{{ cliente.telefone }}</td>
                    <td><a onclick="excluirconfirm(); return false" id="deletar" href="{% url 'espaco:excluircliente' cliente.id %}">X</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</main>

{% endblock content %}

espaco/templates/espaco/pages/home.html
{% extends 'global/base.html' %}
{% load static %}

{% block content %}
    {% include 'espaco/partials/nav.html' %}
    <main>
        <div class="hometudo">
            <div class="fundo_home">
                <div class="body_home">
                    
                    <img class="img_home" src="{% static 'img/logo.png' %}" alt="">
                   <span>TE AJUDO A SUPERAR
                    SEUS TRAUMAS E CONFLITOS EMOCIONAIS
                    Te ajudo a Identificar e Superar suas Dores Emocionais para você se permitir VIVER MELHOR!!!</span>
                </div>
            </div>

        </div>
    </main>
{% endblock content %}

espaco/templates/espaco/pages/meusatendimentos.html
{% extends 'global/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">
{% block content %}
{% include 'espaco/partials/nav.html' %}

<main>
    <div class="atendimentos">
        <div class="atend-recentes">
            <div class="btncli">
                <div class="pesquisa">
                    <form method="GET"action="{% url 'espaco:buscaatend' %}">
                        <div class="form-pesquisa">
                            <input type="search" value="{{ request.GET.termo }}" class="form-control" placeholder="Digite sua pesquisa" name="busca">
                        </div>
                    </form>
                </div>
 
                <button class="btnord">
                    <a href="{% url 'espaco:novoatend' %}">Novo</a>
                </button>
            </div>
            <table class="table-atend">
                <caption>Meus Atendimentos</caption>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>Tecnica</th>
                        <th>Tempo</th>
                        <th>Data</th>
                    </tr>
                </thead>
                <tbody>
                    {% for atendimento in atendimentos %}
                    <tr>
                        <td>{{ atendimento.id }}</td>
                        <td>
                            <a href="{% url 'espaco:veratendimento' atendimento.id %}">{{ atendimento.nome }}</a>
                        </td>
                        <td>{{ atendimento.tecnicaaplicada }}</td>
                        <td>{{ atendimento.tempoconsulta }}</td>
                        <td>{{ atendimento.dataatend }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>    
</main>


{% endblock %}

espaco/templates/espaco/pages/novoatendimento.html
{% extends 'global/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">
{% block content %}
{% include 'espaco/partials/nav.html' %}

    <main>
        <!--<div tabindex="0" onclick="closeSidebar()" class="content" id="content"></div>-->
        <div tabindex="0" onclick="closeSidebar()" id="content" class="container">
            <!--<div class="form-img">
                <img src="{% static 'img/undraw_medicine_b-1-ol.svg' %}" alt="">
            </div>-->
            <div class="form">
                <form method="POST" action="{% url 'espaco:novoatend' %}">
                    {% csrf_token %}
                    <div class="form-header">
                        <div class="title">
                            <h1>ADICIONAR ATENDIMENTO</h1>
                        </div>
                    </div>
                    <div class="input-group">
                        <div class="input-box">
                            <label for="name">Nome</label>
                            <input type="text" name="name" id="name" placeholder="NOME">
                        </div>

                        <div class="input-box">
                            <label for="cpf">CPF</label>
                            <input type="text" name="cpf" id="cpf" placeholder="CPF">
                        </div>

                        

                        <div class="input-box">
                            <label for="tecncaaplicada">Tecnica Aplicada</label>
                            <input type="text" name="tecnicaaplicada" id="tecncaaplicada">
                        </div>
                        

                        <div class="input-box">
                            <label for="tempoconsulta">Tempo Consulta</label>
                            <input type="text" name="tempoconsulta" id="tempoconsulta">
                        </div>

                        <div class="input-box">
                            <label for="queixaprincipal">Queixa Principal</label>
                            <input type="text" name="queixaprincipal" id="queixaprincipal">
                        </div>

                        <div class="input-box">
                            <label for="tempoqueixa">Tempo da Queixa</label>
                            <input type="text" name="tempoqueixa" id="tempoqueixa">
                        </div>


                        <div class="input-box">
                            <label for="tipoconsulta">Tipo de Consulta</label>
                            <select name="tipoconsulta" id="uf">
                                <option value=""></option>
                                <option value="Online">Online</option>
                                <option value="Presencial">Presencial</option>

                            </select>
                        </div>

                        <div class="input-box">
                            <label for="medicamentos">Medicamentos</label>
                            <input type="text" name="medicamentos" id="medicamentos">
                        </div>


                        <div class="input-box" id="obs">
                            <label for="obsatend">Obs Atendimento:</label>
                            <textarea name="obsatend" id="obs" cols="120" rows="10"></textarea>
                        </div>





                    <div class="add-client">
                        <button type="submit"><a href="#"></a>Adicionar Atendimento</button>
                    </div>
                </form>
            </div>
        </div>
    </main>
{% endblock content %}



</html>

espaco/templates/espaco/pages/ver_clientes.html
{% extends 'global/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">
{% block content %}

{% include 'espaco/partials/nav.html' %}
<div class='vertudo'>
    <div class="ajeitar">       
    
        <main>
            
            
            <div class="verclientes">

                
                <div class="btncliente"> 
                    <div class="clientesbuttonedit">
                        <button class"editar"><a href="{% url 'espaco:editarcliente' cliente.id %}">Editar</a></button>
                    </div>
                    <div class="clientesbutton">
                        <button class"excluir"><a onclick="excluirconfirm(); return false" href="{% url 'espaco:excluircliente' cliente.id %}">Excluir</a></button>
                    </div>
            
                </div>  
                <h1 class="clientename">{{ cliente.nome }}</h1>
                <dl class="conteudo">
                <dt>CPF:</dt>
                <dd>{{ cliente.cpf }}</dd>

                <dt>Data de Nascimento:</dt>
                <dd>{{ cliente.datenasc }}</dd>

                <dt>Profissão:</dt>
                <dd>{{ cliente.profissao }}</dd>

                <dt>Endereço:</dt>
                <dd>{{ cliente.endereco }}</dd>

                <dt>Cidade:</dt>
                <dd>{{ cliente.cidade }}</dd>

                <dt>UF:</dt>
                <dd>{{ cliente.uf }}</dd>

                <dt>Pais:</dt>
                <dd>{{ cliente.pais }}</dd>

                <dt>Email:</dt>
                <dd>{{ cliente.email }}</dd>

                <dt>Telefone:</dt>
                <dd>{{ cliente.telefone }}</dd>

                <dt>Genero:</dt>
                <dd>{{ cliente.genero }}</dd>

                <dt>Obs Recepção:</dt>
                <dd>
                    {{ cliente.obsrecepcao }}
                </dd>

                <dt>Filhos:</dt>
                <dd>{{ cliente.filhos }}</dd>

                <dt>Idade:</dt>
                <dd>{{ cliente.idade }}</dd>

                <dt>Opção Sexual:</dt>
                <dd>{{ cliente.opcaosexual }}</dd>

                <dt>Doença Diagnosticada:</dt>
                <dd>{{ cliente.doencadiagnosticada }}</dd>

                <dt>Faz uso de Medicamentos:</dt>
                <dd>{{ cliente.fazusodemedicamentos }}</dd>

                <dt>Obs Terapeuta:</dt>
                <dd>
                    {{ cliente.obsterapeuta }} <br>
                </dd>

                <dt>Obs Complementares:</dt>
                <dd>            
                    {{ cliente.obscomplementares }}
                </dd>




                </dl>
                
    
            </div>
  


    </div> 
        </main>

    </div>   
 
</div>
{% endblock %}

espaco/templates/espaco/pages/veratendimento.html
{% extends 'global/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="pt-Br">
{% block content %}

{% include 'espaco/partials/nav.html' %}
<div class='vertudo'>
    <div class="ajeitar">       
    
        <main>
            
            
            <div class="verclientes">
                
                <div class="btncliente"> 

                    <div class="clientesbuttonedit">
                        <button class"editar"><a href="{% url 'espaco:editaratendimento' atendimento.id %}">Editar</a></button>
                    </div>
                    <div class="clientesbutton">
                        <button class"excluir" ><a onclick="excluirconfirm(); return false" id="deletar" href="{% url 'espaco:excluiratendimento'  atendimento.id%}">Excluir</a></button>
                    </div>



            
                </div>  
                <h1 class="clientename">{{ atendimento.nome }}</h1>
                <dl class="conteudo">
                <dt>CPF:</dt>
                <dd>{{ atendimento.cpf }}</dd>

                <dt>Data do Atendimento:</dt>
                <dd>{{ atendimento.dataatend }}</dd>

                <dt>Tecnica Aplicada:</dt>
                <dd>{{ atendimento.tecnicaaplicada }}</dd>

                <dt>Tipo de Consulta:</dt>
                <dd>{{ atendimento.tipoconsulta }}</dd>

                <dt>Tempo do Atendimento:</dt>
                <dd>{{ atendimento.tempoconsulta }}</dd>

                <dt>Queixa Principal:</dt>
                <dd>{{ atendimento.queixaprincipal }}</dd>


                <dt>Medicamentos:</dt>
                <dd>{{ atendimento.medicamentos }}</dd>


                <dt>Tempo da queixa:</dt>
                <dd>{{ atendimento.tempoqueixa }}</dd>

                <dt>Obs Atendimento:</dt>
                <dd>{{ atendimento.obsatend }}</dd>
                </dl>
    
            </div>
  

        </main>

    </div>   

</div>
{% endblock %}