espaco/urls.py
from django.urls import path

from . import views

app_name = 'espaco'

urlpatterns = [
    path('', views.home),
    path('painel/', views.painel, name='painel'),
    path('clientes/', views.clientes, name='clientes'),
    path('verclientes/<int:pessoa_id>', views.ver_cliente, name='ver_cliente'),
    path('delete/<int:pessoa_id>', views.excluircliente, name='excluircliente'),
    path('editar/<int:pessoa_id>', views.editarcliente, name="editarcliente"),
    path('update/<int:pessoa_id>', views.update, name="update"),
    path('atendimentos/', views.meusatendimentos, name="meusatendimentos"),
    path('busca/', views.busca, name='busca'),
    path('buscaatend/', views.buscaatend, name='buscaatend'),
    path('novoatendimento/', views.novoatend, name='novoatend'),
    path('veratendimento/<atendimento_id>', views.veratendimento, name='veratendimento'),
    path('excluiratendimento/<atendimento_id>', views.excluiratendimento, name='excluiratendimento'),
    path('atendeditar/<int:atendimento_id>', views.editaratendimento, name="editaratendimento"),
    path('atendupdate/<int:atendimento_id>', views.atendupdate, name="atendupdate"),
    


]

pagina/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('espaco.urls')),
    path('usuarios/', include('usuarios.urls'))
]

usuarios/urls.py
from django.urls import path

from . import views

app_name='usuarios'

urlpatterns = [
    path('', views.login, name='index_login'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),


]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render


# Create your views here.
def login(request):
    if request.method != 'POST':
        return render(request, 'usuarios/login.html')
    usuario = request.POST.get('usuario')
    senha = request.POST.get('senha')
    user = auth.authenticate(request, username=usuario, password=senha)
    if not user:
        messages.error(request, 'Usuario ou senha invalidos')
        return render(request, 'usuarios/login.html')
    else:
        auth.login(request, user)
        messages.success(request, 'Voce fez login com sucesso')
        return redirect('espaco:painel')
        
def logout(request):
    auth.logout(request)
    return render(request, 'usuarios/login.html')

usuarios/templates/usuarios/login.html
{% extends 'global/base.html' %}
{% load static %}
{% block content %}

<main>
    <div class="bodylogin">
        <div class="login-tras">
            <form method="POST" action="{% url 'usuarios:login' %}">
                {% csrf_token %}
                <div class="login">
                    <h1>LOGIN</h1>
                    <label for="usuario">Usuario:</label>
                    <input type="text" id="usuario" name="usuario" value="{{request.POST.usuario}}">

                    <label for="senha">Senha:</label>
                    <input name="senha" type="password" id="senha">

                    <button onclick="btnLink()" class="btnlogar">Entrar</button>
                </div>

            </form>
            <div class="imgmao">
                <img src={% static '/img/paralogin.png' %} alt="">
            </div>
        </div>

    </div>

</main>
{% endblock content %}